### ISSUE TITLE
why aren't we allowed to probe the last layer? 

### ISSUE THREAD

**Issue by oserikov** [alexunderch/ASR_probing#3]
https://github.com/alexunderch/ASR_probing/blob/abc52988887fcd2305b7c6b1c96ac479632591df/lib/probers.py#L39

https://github.com/alexunderch/ASR_probing/blob/abc52988887fcd2305b7c6b1c96ac479632591df/lib/probers.py#L64

**Comment by alexunderch** [comment]
you can actually but the 0th and the last layers were off due to debugging and security conditions (hidden size for the last layer could be different, etc). Do I need to fix this for some probers (bert or t5)?

**Comment by alexunderch** [comment]
I did this: https://github.com/alexunderch/ASR_probing/commit/f2c0b0906922d8999a759e281db088f5cb064b6d
However, it is still __prohibited__ to probe the 0-th layer.

**Comment by alexunderch** [comment]
as i have not got any other questions about the issue, i ll close it
